import { create } from "zustand";
const useBotChat = create((set) => ({
  data: [
    {
      chatID: "string",
      timestamp: "ISO 8601 timestamp",
      userID: "string",
      agentID: "string",
      followUpQuestions: ["string", "string", "string"],
      messages: [
        {
          id: 0,
          role: "user",
          content: "string",
          timestamp: "ISO 8601 timestamp",
        },
        {
          id: 1,
          role: "bot",
          content: [
            {
              type: "chart",
              data: {
                data: [
                  {
                    alignmentgroup: "True",
                    hovertemplate:
                      "variable=Group EBIT (before interest in COGS)<br>Time Period=%{x}<br>value=%{y}<extra></extra>",
                    legendgroup: "Group EBIT (before interest in COGS)",
                    marker: {
                      color: "rgb(95, 70, 144)",
                      pattern: { shape: "" },
                    },
                    name: "Group EBIT (before interest in COGS)",
                    offsetgroup: "Group EBIT (before interest in COGS)",
                    orientation: "v",
                    showlegend: true,
                    textposition: "auto",
                    x: ["FY19", "FY20", "FY21", "FY22", "FY23"],
                    xaxis: "x",
                    y: [1079.0, 1046.0, 968.0, 1002.0, 834.0],
                    yaxis: "y",
                    type: "bar",
                  },
                  {
                    alignmentgroup: "True",
                    hovertemplate:
                      "variable=Net interest expense<br>Time Period=%{x}<br>value=%{y}<extra></extra>",
                    legendgroup: "Net interest expense",
                    marker: {
                      color: "rgb(29, 105, 150)",
                      pattern: { shape: "" },
                    },
                    name: "Net interest expense",
                    offsetgroup: "Net interest expense",
                    orientation: "v",
                    showlegend: true,
                    textposition: "auto",
                    x: ["FY19", "FY20", "FY21", "FY22", "FY23"],
                    xaxis: "x",
                    y: [-182.0, -221.0, -180.0, -151.0, -131.0],
                    yaxis: "y",
                    type: "bar",
                  },
                  {
                    alignmentgroup: "True",
                    hovertemplate:
                      "variable=Funds from operations<br>Time Period=%{x}<br>value=%{y}<extra></extra>",
                    legendgroup: "Funds from operations",
                    marker: {
                      color: "rgb(56, 166, 165)",
                      pattern: { shape: "" },
                    },
                    name: "Funds from operations",
                    offsetgroup: "Funds from operations",
                    orientation: "v",
                    showlegend: true,
                    textposition: "auto",
                    x: ["FY19", "FY20", "FY21", "FY22", "FY23"],
                    xaxis: "x",
                    y: [897.0, 825.0, 788.0, 851.0, 702.6],
                    yaxis: "y",
                    type: "bar",
                  },
                  {
                    alignmentgroup: "True",
                    hovertemplate:
                      "variable=Statutory Profit adjustments<br>Time Period=%{x}<br>value=%{y}<extra></extra>",
                    legendgroup: "Statutory Profit adjustments",
                    marker: {
                      color: "rgb(15, 133, 84)",
                      pattern: { shape: "" },
                    },
                    name: "Statutory Profit adjustments",
                    offsetgroup: "Statutory Profit adjustments",
                    orientation: "v",
                    showlegend: true,
                    textposition: "auto",
                    x: ["FY19", "FY20", "FY21", "FY22", "FY23"],
                    xaxis: "x",
                    y: [-586.0, -846.0, 317.0, 530.0, 448.0],
                    yaxis: "y",
                    type: "bar",
                  },
                  {
                    alignmentgroup: "True",
                    hovertemplate:
                      "variable=Statutory Profit<br>Time Period=%{x}<br>value=%{y}<extra></extra>",
                    legendgroup: "Statutory Profit",
                    marker: {
                      color: "rgb(115, 175, 72)",
                      pattern: { shape: "" },
                    },
                    name: "Statutory Profit",
                    offsetgroup: "Statutory Profit",
                    orientation: "v",
                    showlegend: true,
                    textposition: "auto",
                    x: ["FY19", "FY20", "FY21", "FY22", "FY23"],
                    xaxis: "x",
                    y: [311.0, -21.0, 1105.0, 1381.0, 1151.0],
                    yaxis: "y",
                    type: "bar",
                  },
                ],
                layout: {
                  title: "Financial Metrics Over Time",
                  barmode: "group",
                  xaxis: { title: "Time Period" },
                  yaxis: { title: "Value" },
                },
              },
            },
            {
              type: "table",
              data: {
                data: [
                  {
                    "Invoice ID": "39a0cb050c544f5b8de93324ca3d5bde",
                    "Supplier Name": "EBZ SysTec",
                    "Supplier Code": "01749_437810",
                    "Invoice Number": "1220001139",
                    "Invoice Status": "INVOICE_IS_READY_FOR_PAYMENT",
                    "Task Name": "Invoice Saved",
                    "Gross Total": 4140,
                    "Gross Total Company": 58261,
                    "Currency Code": "USD",
                    "Invoice Due Date": "10-May-2022",
                    "Payment Initiated Date": null,
                    "Creation Time": "30-Mar-2022",
                    Recipient: "System",
                  },
                  {
                    "Invoice ID": "a1b2c3d4e5f6g7h8",
                    "Supplier Name": "ACME Corp",
                    "Supplier Code": "12345_67890",
                    "Invoice Number": "1220001140",
                    "Invoice Status": "PAID",
                    "Task Name": "Invoice Processed",
                    "Gross Total": 3200,
                    "Gross Total Company": 65000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "15-May-2022",
                    "Payment Initiated Date": "10-Apr-2022",
                    "Creation Time": "01-Apr-2022",
                    Recipient: "Finance",
                  },
                  {
                    "Invoice ID": "i8h7g6f5e4d3c2b1",
                    "Supplier Name": "XYZ Ltd",
                    "Supplier Code": "54321_09876",
                    "Invoice Number": "1220001141",
                    "Invoice Status": "PENDING",
                    "Task Name": "Invoice Awaiting Approval",
                    "Gross Total": 5800,
                    "Gross Total Company": 72000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "20-May-2022",
                    "Payment Initiated Date": null,
                    "Creation Time": "05-Apr-2022",
                    Recipient: "Manager",
                  },
                  {
                    "Invoice ID": "12345",
                    "Supplier Name": "Tech Corp",
                    "Supplier Code": "00123",
                    "Invoice Number": "1220001142",
                    "Invoice Status": "PAID",
                    "Task Name": "Invoice Approved",
                    "Gross Total": 5000,
                    "Gross Total Company": 70000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "15-Jun-2022",
                    "Payment Initiated Date": "10-May-2022",
                    "Creation Time": "01-May-2022",
                    Recipient: "Finance",
                  },
                  {
                    "Invoice ID": "67890",
                    "Supplier Name": "Auto Parts Ltd.",
                    "Supplier Code": "00234",
                    "Invoice Number": "1220001143",
                    "Invoice Status": "PENDING",
                    "Task Name": "Invoice Under Review",
                    "Gross Total": 3000,
                    "Gross Total Company": 80000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "18-Jun-2022",
                    "Payment Initiated Date": null,
                    "Creation Time": "15-May-2022",
                    Recipient: "Supervisor",
                  },
                  {
                    "Invoice ID": "54321",
                    "Supplier Name": "Furniture Co.",
                    "Supplier Code": "00345",
                    "Invoice Number": "1220001144",
                    "Invoice Status": "PAID",
                    "Task Name": "Invoice Completed",
                    "Gross Total": 4500,
                    "Gross Total Company": 90000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "20-Jul-2022",
                    "Payment Initiated Date": "01-Jul-2022",
                    "Creation Time": "01-Jun-2022",
                    Recipient: "Manager",
                  },
                  {
                    "Invoice ID": "98765",
                    "Supplier Name": "Electro Goods",
                    "Supplier Code": "00456",
                    "Invoice Number": "1220001145",
                    "Invoice Status": "FAILED",
                    "Task Name": "Invoice Failed",
                    "Gross Total": 2500,
                    "Gross Total Company": 100000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "25-Jul-2022",
                    "Payment Initiated Date": null,
                    "Creation Time": "15-Jul-2022",
                    Recipient: "Finance",
                  },
                  {
                    "Invoice ID": "24680",
                    "Supplier Name": "Tools and Hardware",
                    "Supplier Code": "00567",
                    "Invoice Number": "1220001146",
                    "Invoice Status": "PROCESSING",
                    "Task Name": "Invoice Processing",
                    "Gross Total": 6000,
                    "Gross Total Company": 110000,
                    "Currency Code": "USD",
                    "Invoice Due Date": "30-Aug-2022",
                    "Payment Initiated Date": null,
                    "Creation Time": "10-Aug-2022",
                    Recipient: "Operations",
                  },
                ],
                properties: [
                  {
                    headerName: "Invoice ID",
                    field: "Invoice ID",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Supplier Name",
                    field: "Supplier Name",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Supplier Code",
                    field: "Supplier Code",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Invoice Number",
                    field: "Invoice Number",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Invoice Status",
                    field: "Invoice Status",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Task Name",
                    field: "Task Name",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Gross Total",
                    field: "Gross Total",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Currency Code",
                    field: "Currency Code",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Invoice Due Date",
                    field: "Invoice Due Date",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Payment Initiated Date",
                    field: "Payment Initiated Date",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Creation Time",
                    field: "Creation Time",
                    sortable: true,
                    resizable: true,
                  },
                  {
                    headerName: "Recipient",
                    field: "Recipient",
                    sortable: true,
                    resizable: true,
                  },
                ],
              },
            },
            {
              type: "text",
              data: "text Content",
            },
          ],
          debugLog: [
            {
              event: "string",
              timestamp: "ISO 8601 timestamp",
            },
          ],
          timestamp: "ISO 8601 timestamp",
        },
      ],
    },
  ],
}));

export default useBotChat;
